# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "koa"
license = "MIT"
licenselink = "https://github.com/shunkosa/hugo-theme-koa/blob/master/LICENSE.md"
description = "An elegant, mobile-ready, minimalistic theme."
homepage = "https://github.com/shunkosa/hugo-theme-koa/"
tags = ["blog","minimal","responsive","clean","google analytics","syntax highlighting"]
features = ["blog","minimal","responsive","clean","google analytics","syntax highlighting"]
min_version = "0.31"

[author]
  name = "shunkosa"
  homepage = "https://github.com/shunkosa"

# If porting an existing theme
[original]
  name = "resugary"
  homepage = "https://resugary.github.io/hugo-theme-one"
  repo = "https://github.com/resugary/hugo-theme-one"
